global:
  scrape_interval: 15s # How often to scrape targets by default.

scrape_configs:
  - job_name: 'my-app'
    static_configs:
      - targets: ['host.docker.internal:8000'] # Replace with the actual endpoint for your app's metrics.