rules:
  - pattern: "kafka.server<type=(.+), name=(.+)><>Value"
    name: "kafka_server_$1_$2"
    type: GAUGE
    help: "Kafka server $1 $2"
  - pattern: "kafka.network<type=(.+), name=(.+)><>Value"
    name: "kafka_network_$1_$2"
    type: GAUGE
    help: "Kafka network $1 $2"
  - pattern: "kafka.log<type=(.+), name=(.+)><>Value"
    name: "kafka_log_$1_$2"
    type: GAUGE
    help: "Kafka log $1 $2"
  - pattern: "kafka.controller<type=(.+), name=(.+)><>Value"
    name: "kafka_controller_$1_$2"
    type: GAUGE
    help: "Kafka controller $1 $2"
  - pattern: "kafka.cluster<type=(.+), name=(.+)><>Value"
    name: "kafka_cluster_$1_$2"
    type: GAUGE
    help: "Kafka cluster $1 $2"
