{
 "title": "File Storage Service",
 "tags": [
  "core",
  "file-storage"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "file_storage_service_requests_total"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(file_storage_service_request_latency_seconds_sum[5m]) / rate(file_storage_service_request_latency_seconds_count[5m])",
     "legendFormat": "Average Latency"
    }
   ]
  },
  {
   "title": "Success vs Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(file_storage_service_success_total[5m])",
     "legendFormat": "Success Rate"
    },
    {
     "expr": "rate(file_storage_service_errors_total[5m])",
     "legendFormat": "Error Rate"
    }
   ]
  }
 ]
}