# filepath: /home/user/distributed-systems/Distributed_Systems_Group_2/core/prometheus/prometheus.yml
global:
  scrape_interval: 10s # How often to scrape targets by default. Keep short for debugging purposes

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['controller-1:7071', 'controller-2:7072', 'controller-3:7073', 'broker-1:7074', 'broker-2:7075', 'broker-3:7076']
  - job_name: minio-job-cluster
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets: ['minio:9000']
  - job_name: minio-job-node
    metrics_path: /minio/v2/metrics/node
    scheme: http
    static_configs:
      - targets: ['minio:9000']
  - job_name: minio-job-bucket
    metrics_path: /minio/v2/metrics/bucket
    scheme: http
    static_configs:
      - targets: ['minio:9000']
  - job_name: minio-job-resource
    metrics_path: /minio/v2/metrics/resource
    scheme: http
    static_configs:
      - targets: ['minio:9000']