apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-service
  template:
    metadata:
      labels:
        app: database-service
    spec:
      containers:
        - name: database-service
          image: matluuk/ds-database-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8011
          env:
            - name: MONGODB_URL
              value: "mongodb://mongodb:27017/?directConnection=true"
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  ports:
    - port: 8011
      targetPort: 8011
  selector:
    app: database-service