apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-storage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-storage-service
  template:
    metadata:
      labels:
        app: file-storage-service
    spec:
      containers:
        - name: file-storage-service
          image: matluuk/ds-file-storage-service
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_PASSWORD
            - name: MINIO_ENDPOINT
              value: "minio:9000"
---
apiVersion: v1
kind: Service
metadata:
  name: file-storage-service
spec:
  ports:
    - port: 50051
      targetPort: 50051
  selector:
    app: file-storage-service