apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-storage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-storage-service
  template:
    metadata:
      labels:
        app: file-storage-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: file-storage-service
          image: matluuk/ds-file-storage-service
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
            - containerPort: 8000
              name: metrics
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_PASSWORD
            - name: MINIO_ENDPOINT
              value: "http://195.148.22.181/minio"
---
apiVersion: v1
kind: Service
metadata:
  name: file-storage-service
spec:
  type: NodePort
  ports:
    - port: 50051
      targetPort: 50051
      nodePort: 30002
      name: grpc # Add a name for the gRPC port
    - port: 8000
      targetPort: 8000
      nodePort: 30003
      name: metrics
  selector:
    app: file-storage-service
