apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090
  selector:
    app: prometheus
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    # filepath: /home/user/distributed-systems/Distributed_Systems_Group_2/core/prometheus/prometheus.yml
    global:
      scrape_interval: 10s # How often to scrape targets by default. Keep short for debugging purposes

    scrape_configs:
      - job_name: 'kafka'
        static_configs:
          - targets: ['kafka:7071']
      - job_name: minio-job-cluster
        metrics_path: /minio/v2/metrics/cluster
        scheme: http
        static_configs:
          - targets: ['minio:9000']
      - job_name: minio-job-node
        metrics_path: /minio/v2/metrics/node
        scheme: http
        static_configs:
          - targets: ['minio:9000']
      - job_name: minio-job-bucket
        metrics_path: /minio/v2/metrics/bucket
        scheme: http
        static_configs:
          - targets: ['minio:9000']
      - job_name: minio-job-resource
        metrics_path: /minio/v2/metrics/resource
        scheme: http
        static_configs:
          - targets: ['minio:9000']
      - job_name: file-storage-service
        static_configs:
          - targets: ['file-storage-service:8000']
      - job_name: video-uploader
        static_configs:
          - targets: ['video-uploader:8000']
      - job_name: request-controller
        static_configs:
          - targets: ['request-controller:8080']
      - job_name: database-service
        static_configs:
          - targets: ['database-service:8011']