apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request-controller
  template:
    metadata:
      labels:
        app: request-controller
    spec:
      containers:
        - name: request-controller
          image: matluuk/ds-request-controller
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_SERVICE_URL
              value: "http://database-service:8011"
---
apiVersion: v1
kind: Service
metadata:
  name: request-controller
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 8080
  selector:
    app: request-controller