apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-uploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-uploader
  template:
    metadata:
      labels:
        app: video-uploader
    spec:
      containers:
        - name: video-uploader
          image: matluuk/ds-video-uploader
          ports:
            - containerPort: 8000
          env:
            - name: MINIO_ENDPOINT
              value: "minio:9000"
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_PASSWORD
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "broker-1:9092,broker-2:9092,broker-3:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: video-uploader
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: video-uploader