# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: streaming.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstreaming.proto\x12\tstreaming\"!\n\rStreamRequest\x12\x10\n\x08video_id\x18\x01 \x01(\t\":\n\x0eStreamResponse\x12\x12\n\nstream_url\x18\x01 \x01(\t\x12\x14\n\x0c\x65\x64ge_node_id\x18\x02 \x01(\t\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32\x9c\x01\n\x10StreamingService\x12\x42\n\tGetStream\x12\x18.streaming.StreamRequest\x1a\x19.streaming.StreamResponse\"\x00\x12\x44\n\x0bHealthCheck\x12\x18.streaming.HealthRequest\x1a\x19.streaming.HealthResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMREQUEST']._serialized_start=30
  _globals['_STREAMREQUEST']._serialized_end=63
  _globals['_STREAMRESPONSE']._serialized_start=65
  _globals['_STREAMRESPONSE']._serialized_end=123
  _globals['_HEALTHREQUEST']._serialized_start=125
  _globals['_HEALTHREQUEST']._serialized_end=140
  _globals['_HEALTHRESPONSE']._serialized_start=142
  _globals['_HEALTHRESPONSE']._serialized_end=174
  _globals['_STREAMINGSERVICE']._serialized_start=177
  _globals['_STREAMINGSERVICE']._serialized_end=333
# @@protoc_insertion_point(module_scope)
