# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: presigner.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'presigner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpresigner.proto\x12\tpresigner\"+\n\x17VideoDownloadUrlRequest\x12\x10\n\x08video_id\x18\x01 \x01(\t\"0\n\x18VideoDownloadUrlResponse\x12\x14\n\x0c\x64ownload_url\x18\x01 \x01(\t2r\n\x10PresignerService\x12^\n\x13GetVideoDownloadUrl\x12\".presigner.VideoDownloadUrlRequest\x1a#.presigner.VideoDownloadUrlResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'presigner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIDEODOWNLOADURLREQUEST']._serialized_start=30
  _globals['_VIDEODOWNLOADURLREQUEST']._serialized_end=73
  _globals['_VIDEODOWNLOADURLRESPONSE']._serialized_start=75
  _globals['_VIDEODOWNLOADURLRESPONSE']._serialized_end=123
  _globals['_PRESIGNERSERVICE']._serialized_start=125
  _globals['_PRESIGNERSERVICE']._serialized_end=239
# @@protoc_insertion_point(module_scope)
