# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ai_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61i_service.proto\x12\x06openai\"\x1e\n\tAIRequest\x12\x11\n\tjson_data\x18\x01 \x01(\t\"#\n\nAIResponse\x12\x15\n\rjson_response\x18\x01 \x01(\t2J\n\rOpenAIService\x12\x39\n\x0eProcessRequest\x12\x11.openai.AIRequest\x1a\x12.openai.AIResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AIREQUEST']._serialized_start=28
  _globals['_AIREQUEST']._serialized_end=58
  _globals['_AIRESPONSE']._serialized_start=60
  _globals['_AIRESPONSE']._serialized_end=95
  _globals['_OPENAISERVICE']._serialized_start=97
  _globals['_OPENAISERVICE']._serialized_end=171
# @@protoc_insertion_point(module_scope)
