# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import file_storage_service_pb2 as file__storage__service__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in file_storage_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FileStorageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVideoDownloadUrl = channel.unary_unary(
                '/file_storage.FileStorageService/GetVideoDownloadUrl',
                request_serializer=file__storage__service__pb2.VideoDownloadUrlRequest.SerializeToString,
                response_deserializer=file__storage__service__pb2.VideoDownloadUrlResponse.FromString,
                _registered_method=True)


class FileStorageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetVideoDownloadUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileStorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetVideoDownloadUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVideoDownloadUrl,
                    request_deserializer=file__storage__service__pb2.VideoDownloadUrlRequest.FromString,
                    response_serializer=file__storage__service__pb2.VideoDownloadUrlResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'file_storage.FileStorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('file_storage.FileStorageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileStorageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetVideoDownloadUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file_storage.FileStorageService/GetVideoDownloadUrl',
            file__storage__service__pb2.VideoDownloadUrlRequest.SerializeToString,
            file__storage__service__pb2.VideoDownloadUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
