apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
type: Opaque
data:
  # Replace with your base64 encoded API key: echo -n "your-api-key" | base64
  OPENAI_API_KEY: c2stcHJvai1EenMyWE9kS3pkVFlTNEx5dmZRaWhralM1UUo0TUNITGRiYzgxSVdwcmhwVl9rMWxLT3J3SFlVWHZVeE9oVkVScktiS2w5OC1SVVQzQmxia0ZKLVktVW83NlVKUC04cWZRMS0yTlNXbWtYeWlZenlLRzJiZlZBNl9LTEtYUXZUejZBVXFuYU5WajVBN1ZmQ29tZjZ0OWpwbXZjb0E=

---
apiVersion: v1
kind: Service
metadata:
  name: grpc-openai-service
spec:
  selector:
    app: grpc-openai
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-openai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grpc-openai
  template:
    metadata:
      labels:
        app: grpc-openai
    spec:
      containers:
        - name: grpc-openai
          image: hasaan12/grpc-openai:latest
          ports:
            - containerPort: 50051
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: OPENAI_API_KEY
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          livenessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: grpc-openai-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grpc-openai
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
