apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - "--web.listen-address=0.0.0.0:9091"
            - "--config.file=/etc/prometheus/prometheus.yml"
          ports:
            - containerPort: 9091
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 10s
    scrape_configs:
      # MinIO Metrics
      - job_name: minio-job-cluster
        metrics_path: /minio/v2/metrics/cluster
        scheme: http
        static_configs:
          - targets: ["minio:9000"]
      - job_name: minio-job-node
        metrics_path: /minio/v2/metrics/node
        scheme: http
        static_configs:
          - targets: ["minio:9000"]
      - job_name: minio-job-bucket
        metrics_path: /minio/v2/metrics/bucket
        scheme: http
        static_configs:
          - targets: ["minio:9000"]
      - job_name: minio-job-resource
        metrics_path: /minio/v2/metrics/resource
        scheme: http
        static_configs:
          - targets: ["minio:9000"]
      
      # Cache Controller Metrics
      - job_name: cache-controller
        metrics_path: /metrics
        scrape_interval: 5s
        static_configs:
          - targets: ["cache-controller:5001"]
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            replacement: cache-controller
          - source_labels: [__address__]
            target_label: service
            replacement: cache-service

      # Redis Metrics
      - job_name: redis
        static_configs:
          - targets: ["redis-exporter:9121"]
        metrics_path: /metrics
        scrape_interval: 5s
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            replacement: redis
          - source_labels: [__address__]
            target_label: service
            replacement: cache-db

      # Streaming Controller Metrics
      - job_name: streaming-controller
        metrics_path: /metrics
        scrape_interval: 5s
        static_configs:
          - targets: ["streaming-controller:8000"]
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            replacement: streaming-controller
          - source_labels: [__address__]
            target_label: service
            replacement: streaming-service
      - job_name: prometheus
        static_configs:
          - targets: ["localhost:9091"]
      - job_name: grafana
        static_configs:
          - targets: ["grafana:3333"]
