apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hls-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-controller
  labels:
    app: streaming-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming-controller
  template:
    metadata:
      labels:
        app: streaming-controller
    spec:
      containers:
        - name: streaming-controller
          image: hasaan12/ds-streaming-controller:latest
          ports:
            - containerPort: 8000
          env:
            - name: MINIO_HOST
              value: "minio"
            - name: MINIO_PORT
              value: "9000"
            - name: MINIO_HOST_CORE
              value: "195.148.22.181"
            - name: MINIO_PORT_CORE
              value: "30900"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: root-user
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: root-password
            - name: MINIO_BUCKET
              value: "cache"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: hls-storage
              mountPath: /tmp/hls_videos
      volumes:
        - name: hls-storage
          persistentVolumeClaim:
            claimName: hls-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: streaming-controller
spec:
  selector:
    app: streaming-controller
  ports:
    - port: 8054
      targetPort: 8000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: streaming-controller-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: streaming-controller
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
